meta_product_name: "fourfive cbd"
meta_title: "fourfive cbd - Rest, recover and rise"
meta_description: "To help you maintain an active lifestyle"
meta_image: "carousel-mobile.jpg" # should exist in `app/assets/images/`
twitter_account: "@fourfivecbd"   # required for Twitter Cards
