meta_product_name: "Fourfive cbd"
meta_title: "Fourfive cbd"
meta_description: "To help you maintain an active lifestyle"
meta_image: "carousel-mobile.jpg" # should exist in `app/assets/images/`
twitter_account: "@fourfivecbd"   # required for Twitter Cards
